name = "MyChebyshev"
uuid = "2decbe97-afac-4190-809a-1eeb7bb9f0ac"
authors = ["Samuel Higbee <samuelhigbee@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
